apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: hello-pipeline-run
spec:
  pipelineRef:
    name: hello-pipeline

  podTemplate:
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000 #tsuji
      seccompProfile:
        type: RuntimeDefault

  taskRunTemplate:
    podTemplate:
      securityContext:
        fsGroup: 1000
